version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: .bundle
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: install bundle
          command: bundle install
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: install yarn
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: run tests
          command: |
            bundle exec rake test
            bundle exec rake test:system
      - store_test_results:
          path: test/reports
  deploy:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: .bundle
          RAILS_ENV: production
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: install bundle
          command: bundle install
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: install yarn
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - add_ssh_keys:
          fingerprints:
            - "91:5b:7f:10:ad:ce:3b:67:7f:7e:bf:50:f6:25:ab:5c"
      - run:
          name: deploy by ssh
          command: |
            bundle exec cap production deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
